packages:
  - apps/*
  - packages/*
  - e2e

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - '@swc/core'
  - '@nestjs/core'
  - esbuild
  - bcrypt
  - sharp
  - unrs-resolver
